INSERT INTO city ("name",province_id,"created_at","modified_at", now(), now()) VALUES 
('Bone Bolango',7, now(), now())
,('Aceh Barat',21, now(), now())
,('Aceh Barat Daya',21, now(), now())
,('Aceh Besar',21, now(), now())
,('Aceh Jaya',21, now(), now())
,('Aceh Selatan',21, now(), now())
,('Aceh Singkil',21, now(), now())
,('Aceh Tamiang',21, now(), now())
,('Aceh Tengah',21, now(), now())
,('Aceh Tenggara',21, now(), now())
,('Aceh Timur',21, now(), now())
,('Aceh Utara',21, now(), now())
,('Agam',32, now(), now())
,('Alor',23, now(), now())
,('Ambon',19, now(), now())
,('Asahan',34, now(), now())
,('Asmat',24, now(), now())
,('Badung',1, now(), now())
,('Balangan',13, now(), now())
,('Balikpapan',15, now(), now())
,('Banda Aceh',21, now(), now())
,('Bandar Lampung',18, now(), now())
,('Bandung',9, now(), now())
,('Bandung',9, now(), now())
,('Bandung Barat',9, now(), now())
,('Banggai',29, now(), now())
,('Banggai Kepulauan',29, now(), now())
,('Bangka',2, now(), now())
,('Bangka Barat',2, now(), now())
,('Bangka Selatan',2, now(), now())
,('Bangka Tengah',2, now(), now())
,('Bangkalan',11, now(), now())
,('Bangli',1, now(), now())
,('Banjar',13, now(), now())
,('Banjar',9, now(), now())
,('Banjarbaru',13, now(), now())
,('Banjarmasin',13, now(), now())
,('Banjarnegara',10, now(), now())
,('Bantaeng',28, now(), now())
,('Bantul',5, now(), now())
,('Banyuasin',33, now(), now())
,('Banyumas',10, now(), now())
,('Banyuwangi',11, now(), now())
,('Barito Kuala',13, now(), now())
,('Barito Selatan',14, now(), now())
,('Barito Timur',14, now(), now())
,('Barito Utara',14, now(), now())
,('Barru',28, now(), now())
,('Batam',17, now(), now())
,('Batang',10, now(), now())
,('Batang Hari',8, now(), now())
,('Batu',11, now(), now())
,('Batu Bara',34, now(), now())
,('Bau-Bau',30, now(), now())
,('Bekasi',9, now(), now())
,('Bekasi',9, now(), now())
,('Belitung',2, now(), now())
,('Belitung Timur',2, now(), now())
,('Belu',23, now(), now())
,('Bener Meriah',21, now(), now())
,('Bengkalis',26, now(), now())
,('Bengkayang',12, now(), now())
,('Bengkulu',4, now(), now())
,('Bengkulu Selatan',4, now(), now())
,('Bengkulu Tengah',4, now(), now())
,('Bengkulu Utara',4, now(), now())
,('Berau',15, now(), now())
,('Biak Numfor',24, now(), now())
,('Bima',22, now(), now())
,('Bima',22, now(), now())
,('Binjai',34, now(), now())
,('Bintan',17, now(), now())
,('Bireuen',21, now(), now())
,('Bitung',31, now(), now())
,('Blitar',11, now(), now())
,('Blitar',11, now(), now())
,('Blora',10, now(), now())
,('Boalemo',7, now(), now())
,('Bogor',9, now(), now())
,('Bogor',9, now(), now())
,('Bojonegoro',11, now(), now())
,('Bolaang Mongondow (Bolmong)',31, now(), now())
,('Bolaang Mongondow Selatan',31, now(), now())
,('Bolaang Mongondow Timur',31, now(), now())
,('Bolaang Mongondow Utara',31, now(), now())
,('Bombana',30, now(), now())
,('Bondowoso',11, now(), now())
,('Bone',28, now(), now())
,('Bontang',15, now(), now())
,('Boven Digoel',24, now(), now())
,('Boyolali',10, now(), now())
,('Brebes',10, now(), now())
,('Bukittinggi',32, now(), now())
,('Buleleng',1, now(), now())
,('Bulukumba',28, now(), now())
,('Bulungan (Bulongan)',16, now(), now())
,('Bungo',8, now(), now())
,('Buol',29, now(), now())
,('Buru',19, now(), now())
,('Buru Selatan',19, now(), now())
,('Buton',30, now(), now())
,('Buton Utara',30, now(), now())
,('Ciamis',9, now(), now())
,('Cianjur',9, now(), now())
,('Cilacap',10, now(), now())
,('Cilegon',3, now(), now())
,('Cimahi',9, now(), now())
,('Cirebon',9, now(), now())
,('Cirebon',9, now(), now())
,('Dairi',34, now(), now())
,('Deiyai (Deliyai)',24, now(), now())
,('Deli Serdang',34, now(), now())
,('Demak',10, now(), now())
,('Denpasar',1, now(), now())
,('Depok',9, now(), now())
,('Dharmasraya',32, now(), now())
,('Dogiyai',24, now(), now())
,('Dompu',22, now(), now())
,('Donggala',29, now(), now())
,('Dumai',26, now(), now())
,('Empat Lawang',33, now(), now())
,('Ende',23, now(), now())
,('Enrekang',28, now(), now())
,('Fakfak',25, now(), now())
,('Flores Timur',23, now(), now())
,('Garut',9, now(), now())
,('Gayo Lues',21, now(), now())
,('Gianyar',1, now(), now())
,('Gorontalo',7, now(), now())
,('Gorontalo',7, now(), now())
,('Gorontalo Utara',7, now(), now())
,('Gowa',28, now(), now())
,('Gresik',11, now(), now())
,('Grobogan',10, now(), now())
,('Gunung Kidul',5, now(), now())
,('Gunung Mas',14, now(), now())
,('Gunungsitoli',34, now(), now())
,('Halmahera Barat',20, now(), now())
,('Halmahera Selatan',20, now(), now())
,('Halmahera Tengah',20, now(), now())
,('Halmahera Timur',20, now(), now())
,('Halmahera Utara',20, now(), now())
,('Hulu Sungai Selatan',13, now(), now())
,('Hulu Sungai Tengah',13, now(), now())
,('Hulu Sungai Utara',13, now(), now())
,('Humbang Hasundutan',34, now(), now())
,('Indragiri Hilir',26, now(), now())
,('Indragiri Hulu',26, now(), now())
,('Indramayu',9, now(), now())
,('Intan Jaya',24, now(), now())
,('Jakarta Barat',6, now(), now())
,('Jakarta Pusat',6, now(), now())
,('Jakarta Selatan',6, now(), now())
,('Jakarta Timur',6, now(), now())
,('Jakarta Utara',6, now(), now())
,('Jambi',8, now(), now())
,('Jayapura',24, now(), now())
,('Jayapura',24, now(), now())
,('Jayawijaya',24, now(), now())
,('Jember',11, now(), now())
,('Jembrana',1, now(), now())
,('Jeneponto',28, now(), now())
,('Jepara',10, now(), now())
,('Jombang',11, now(), now())
,('Kaimana',25, now(), now())
,('Kampar',26, now(), now())
,('Kapuas',14, now(), now())
,('Kapuas Hulu',12, now(), now())
,('Karanganyar',10, now(), now())
,('Karangasem',1, now(), now())
,('Karawang',9, now(), now())
,('Karimun',17, now(), now())
,('Karo',34, now(), now())
,('Katingan',14, now(), now())
,('Kaur',4, now(), now())
,('Kayong Utara',12, now(), now())
,('Kebumen',10, now(), now())
,('Kediri',11, now(), now())
,('Kediri',11, now(), now())
,('Keerom',24, now(), now())
,('Kendal',10, now(), now())
,('Kendari',30, now(), now())
,('Kepahiang',4, now(), now())
,('Kepulauan Anambas',17, now(), now())
,('Kepulauan Aru',19, now(), now())
,('Kepulauan Mentawai',32, now(), now())
,('Kepulauan Meranti',26, now(), now())
,('Kepulauan Sangihe',31, now(), now())
,('Kepulauan Seribu',6, now(), now())
,('Kepulauan Siau Tagulandang Biaro (Sitaro)',31, now(), now())
,('Kepulauan Sula',20, now(), now())
,('Kepulauan Talaud',31, now(), now())
,('Kepulauan Yapen (Yapen Waropen)',24, now(), now())
,('Kerinci',8, now(), now())
,('Ketapang',12, now(), now())
,('Klaten',10, now(), now())
,('Klungkung',1, now(), now())
,('Kolaka',30, now(), now())
,('Kolaka Utara',30, now(), now())
,('Konawe',30, now(), now())
,('Konawe Selatan',30, now(), now())
,('Konawe Utara',30, now(), now())
,('Kotabaru',13, now(), now())
,('Kotamobagu',31, now(), now())
,('Kotawaringin Barat',14, now(), now())
,('Kotawaringin Timur',14, now(), now())
,('Kuantan Singingi',26, now(), now())
,('Kubu Raya',12, now(), now())
,('Kudus',10, now(), now())
,('Kulon Progo',5, now(), now())
,('Kuningan',9, now(), now())
,('Kupang',23, now(), now())
,('Kupang',23, now(), now())
,('Kutai Barat',15, now(), now())
,('Kutai Kartanegara',15, now(), now())
,('Kutai Timur',15, now(), now())
,('Labuhan Batu',34, now(), now())
,('Labuhan Batu Selatan',34, now(), now())
,('Labuhan Batu Utara',34, now(), now())
,('Lahat',33, now(), now())
,('Lamandau',14, now(), now())
,('Lamongan',11, now(), now())
,('Lampung Barat',18, now(), now())
,('Lampung Selatan',18, now(), now())
,('Lampung Tengah',18, now(), now())
,('Lampung Timur',18, now(), now())
,('Lampung Utara',18, now(), now())
,('Landak',12, now(), now())
,('Langkat',34, now(), now())
,('Langsa',21, now(), now())
,('Lanny Jaya',24, now(), now())
,('Lebak',3, now(), now())
,('Lebong',4, now(), now())
,('Lembata',23, now(), now())
,('Lhokseumawe',21, now(), now())
,('Lima Puluh Koto/Kota',32, now(), now())
,('Lingga',17, now(), now())
,('Lombok Barat',22, now(), now())
,('Lombok Tengah',22, now(), now())
,('Lombok Timur',22, now(), now())
,('Lombok Utara',22, now(), now())
,('Lubuk Linggau',33, now(), now())
,('Lumajang',11, now(), now())
,('Luwu',28, now(), now())
,('Luwu Timur',28, now(), now())
,('Luwu Utara',28, now(), now())
,('Madiun',11, now(), now())
,('Madiun',11, now(), now())
,('Magelang',10, now(), now())
,('Magelang',10, now(), now())
,('Magetan',11, now(), now())
,('Majalengka',9, now(), now())
,('Majene',27, now(), now())
,('Makassar',28, now(), now())
,('Malang',11, now(), now())
,('Malang',11, now(), now())
,('Malinau',16, now(), now())
,('Maluku Barat Daya',19, now(), now())
,('Maluku Tengah',19, now(), now())
,('Maluku Tenggara',19, now(), now())
,('Maluku Tenggara Barat',19, now(), now())
,('Mamasa',27, now(), now())
,('Mamberamo Raya',24, now(), now())
,('Mamberamo Tengah',24, now(), now())
,('Mamuju',27, now(), now())
,('Mamuju Utara',27, now(), now())
,('Manado',31, now(), now())
,('Mandailing Natal',34, now(), now())
,('Manggarai',23, now(), now())
,('Manggarai Barat',23, now(), now())
,('Manggarai Timur',23, now(), now())
,('Manokwari',25, now(), now())
,('Manokwari Selatan',25, now(), now())
,('Mappi',24, now(), now())
,('Maros',28, now(), now())
,('Mataram',22, now(), now())
,('Maybrat',25, now(), now())
,('Medan',34, now(), now())
,('Melawi',12, now(), now())
,('Merangin',8, now(), now())
,('Merauke',24, now(), now())
,('Mesuji',18, now(), now())
,('Metro',18, now(), now())
,('Mimika',24, now(), now())
,('Minahasa',31, now(), now())
,('Minahasa Selatan',31, now(), now())
,('Minahasa Tenggara',31, now(), now())
,('Minahasa Utara',31, now(), now())
,('Mojokerto',11, now(), now())
,('Mojokerto',11, now(), now())
,('Morowali',29, now(), now())
,('Muara Enim',33, now(), now())
,('Muaro Jambi',8, now(), now())
,('Muko Muko',4, now(), now())
,('Muna',30, now(), now())
,('Murung Raya',14, now(), now())
,('Musi Banyuasin',33, now(), now())
,('Musi Rawas',33, now(), now())
,('Nabire',24, now(), now())
,('Nagan Raya',21, now(), now())
,('Nagekeo',23, now(), now())
,('Natuna',17, now(), now())
,('Nduga',24, now(), now())
,('Ngada',23, now(), now())
,('Nganjuk',11, now(), now())
,('Ngawi',11, now(), now())
,('Nias',34, now(), now())
,('Nias Barat',34, now(), now())
,('Nias Selatan',34, now(), now())
,('Nias Utara',34, now(), now())
,('Nunukan',16, now(), now())
,('Ogan Ilir',33, now(), now())
,('Ogan Komering Ilir',33, now(), now())
,('Ogan Komering Ulu',33, now(), now())
,('Ogan Komering Ulu Selatan',33, now(), now())
,('Ogan Komering Ulu Timur',33, now(), now())
,('Pacitan',11, now(), now())
,('Padang',32, now(), now())
,('Padang Lawas',34, now(), now())
,('Padang Lawas Utara',34, now(), now())
,('Padang Panjang',32, now(), now())
,('Padang Pariaman',32, now(), now())
,('Padang Sidempuan',34, now(), now())
,('Pagar Alam',33, now(), now())
,('Pakpak Bharat',34, now(), now())
,('Palangka Raya',14, now(), now())
,('Palembang',33, now(), now())
,('Palopo',28, now(), now())
,('Palu',29, now(), now())
,('Pamekasan',11, now(), now())
,('Pandeglang',3, now(), now())
,('Pangandaran',9, now(), now())
,('Pangkajene Kepulauan',28, now(), now())
,('Pangkal Pinang',2, now(), now())
,('Paniai',24, now(), now())
,('Parepare',28, now(), now())
,('Pariaman',32, now(), now())
,('Parigi Moutong',29, now(), now())
,('Pasaman',32, now(), now())
,('Pasaman Barat',32, now(), now())
,('Paser',15, now(), now())
,('Pasuruan',11, now(), now())
,('Pasuruan',11, now(), now())
,('Pati',10, now(), now())
,('Payakumbuh',32, now(), now())
,('Pegunungan Arfak',25, now(), now())
,('Pegunungan Bintang',24, now(), now())
,('Pekalongan',10, now(), now())
,('Pekalongan',10, now(), now())
,('Pekanbaru',26, now(), now())
,('Pelalawan',26, now(), now())
,('Pemalang',10, now(), now())
,('Pematang Siantar',34, now(), now())
,('Penajam Paser Utara',15, now(), now())
,('Pesawaran',18, now(), now())
,('Pesisir Barat',18, now(), now())
,('Pesisir Selatan',32, now(), now())
,('Pidie',21, now(), now())
,('Pidie Jaya',21, now(), now())
,('Pinrang',28, now(), now())
,('Pohuwato',7, now(), now())
,('Polewali Mandar',27, now(), now())
,('Ponorogo',11, now(), now())
,('Pontianak',12, now(), now())
,('Pontianak',12, now(), now())
,('Poso',29, now(), now())
,('Prabumulih',33, now(), now())
,('Pringsewu',18, now(), now())
,('Probolinggo',11, now(), now())
,('Probolinggo',11, now(), now())
,('Pulang Pisau',14, now(), now())
,('Pulau Morotai',20, now(), now())
,('Puncak',24, now(), now())
,('Puncak Jaya',24, now(), now())
,('Purbalingga',10, now(), now())
,('Purwakarta',9, now(), now())
,('Purworejo',10, now(), now())
,('Raja Ampat',25, now(), now())
,('Rejang Lebong',4, now(), now())
,('Rembang',10, now(), now())
,('Rokan Hilir',26, now(), now())
,('Rokan Hulu',26, now(), now())
,('Rote Ndao',23, now(), now())
,('Sabang',21, now(), now())
,('Sabu Raijua',23, now(), now())
,('Salatiga',10, now(), now())
,('Samarinda',15, now(), now())
,('Sambas',12, now(), now())
,('Samosir',34, now(), now())
,('Sampang',11, now(), now())
,('Sanggau',12, now(), now())
,('Sarmi',24, now(), now())
,('Sarolangun',8, now(), now())
,('Sawah Lunto',32, now(), now())
,('Sekadau',12, now(), now())
,('Selayar (Kepulauan Selayar)',28, now(), now())
,('Seluma',4, now(), now())
,('Semarang',10, now(), now())
,('Semarang',10, now(), now())
,('Seram Bagian Barat',19, now(), now())
,('Seram Bagian Timur',19, now(), now())
,('Serang',3, now(), now())
,('Serang',3, now(), now())
,('Serdang Bedagai',34, now(), now())
,('Seruyan',14, now(), now())
,('Siak',26, now(), now())
,('Sibolga',34, now(), now())
,('Sidenreng Rappang/Rapang',28, now(), now())
,('Sidoarjo',11, now(), now())
,('Sigi',29, now(), now())
,('Sijunjung (Sawah Lunto Sijunjung)',32, now(), now())
,('Sikka',23, now(), now())
,('Simalungun',34, now(), now())
,('Simeulue',21, now(), now())
,('Singkawang',12, now(), now())
,('Sinjai',28, now(), now())
,('Sintang',12, now(), now())
,('Situbondo',11, now(), now())
,('Sleman',5, now(), now())
,('Solok',32, now(), now())
,('Solok',32, now(), now())
,('Solok Selatan',32, now(), now())
,('Soppeng',28, now(), now())
,('Sorong',25, now(), now())
,('Sorong',25, now(), now())
,('Sorong Selatan',25, now(), now())
,('Sragen',10, now(), now())
,('Subang',9, now(), now())
,('Subulussalam',21, now(), now())
,('Sukabumi',9, now(), now())
,('Sukabumi',9, now(), now())
,('Sukamara',14, now(), now())
,('Sukoharjo',10, now(), now())
,('Sumba Barat',23, now(), now())
,('Sumba Barat Daya',23, now(), now())
,('Sumba Tengah',23, now(), now())
,('Sumba Timur',23, now(), now())
,('Sumbawa',22, now(), now())
,('Sumbawa Barat',22, now(), now())
,('Sumedang',9, now(), now())
,('Sumenep',11, now(), now())
,('Sungaipenuh',8, now(), now())
,('Supiori',24, now(), now())
,('Surabaya',11, now(), now())
,('Surakarta (Solo)',10, now(), now())
,('Tabalong',13, now(), now())
,('Tabanan',1, now(), now())
,('Takalar',28, now(), now())
,('Tambrauw',25, now(), now())
,('Tana Tidung',16, now(), now())
,('Tana Toraja',28, now(), now())
,('Tanah Bumbu',13, now(), now())
,('Tanah Datar',32, now(), now())
,('Tanah Laut',13, now(), now())
,('Tangerang',3, now(), now())
,('Tangerang',3, now(), now())
,('Tangerang Selatan',3, now(), now())
,('Tanggamus',18, now(), now())
,('Tanjung Balai',34, now(), now())
,('Tanjung Jabung Barat',8, now(), now())
,('Tanjung Jabung Timur',8, now(), now())
,('Tanjung Pinang',17, now(), now())
,('Tapanuli Selatan',34, now(), now())
,('Tapanuli Tengah',34, now(), now())
,('Tapanuli Utara',34, now(), now())
,('Tapin',13, now(), now())
,('Tarakan',16, now(), now())
,('Tasikmalaya',9, now(), now())
,('Tasikmalaya',9, now(), now())
,('Tebing Tinggi',34, now(), now())
,('Tebo',8, now(), now())
,('Tegal',10, now(), now())
,('Tegal',10, now(), now())
,('Teluk Bintuni',25, now(), now())
,('Teluk Wondama',25, now(), now())
,('Temanggung',10, now(), now())
,('Ternate',20, now(), now())
,('Tidore Kepulauan',20, now(), now())
,('Timor Tengah Selatan',23, now(), now())
,('Timor Tengah Utara',23, now(), now())
,('Toba Samosir',34, now(), now())
,('Tojo Una-Una',29, now(), now())
,('Toli-Toli',29, now(), now())
,('Tolikara',24, now(), now())
,('Tomohon',31, now(), now())
,('Toraja Utara',28, now(), now())
,('Trenggalek',11, now(), now())
,('Tual',19, now(), now())
,('Tuban',11, now(), now())
,('Tulang Bawang',18, now(), now())
,('Tulang Bawang Barat',18, now(), now())
,('Tulungagung',11, now(), now())
,('Wajo',28, now(), now())
,('Wakatobi',30, now(), now())
,('Waropen',24, now(), now())
,('Way Kanan',18, now(), now())
,('Wonogiri',10, now(), now())
,('Wonosobo',10, now(), now())
,('Yahukimo',24, now(), now())
,('Yalimo',24, now(), now())
,('Yogyakarta',5, now(), now());